### ISSUE TITLE
Clarification needed on REF_PATH file format for 'psite train' command

### ISSUE THREAD

**Issue by mrvictorica** [gxelab/psite#1]
Hi!

I've installed PSite and been trying it out for a couple of days now. Unluckily, I'm not getting past the very first "train" step. As found in the documentation, the train command takes these inputs and arguments:

`psite train [OPTIONS] PATH_REF PATH_BAM OUTPUT_PREFIX PATH_TXINFO`

I would kindly ask for your assistance in informing me what type of file is **PATH_REF**. According to the readme instructive, it corresponds to the _sequences of all transcripts_ in the alignment AND the _reference transcriptome (fasta) matching the bam_, which for me are different things.

I've used bedtools' function _getfasta_ to extract the sequences from the human reference genome that matched my alignment's GTF file, and that way obtain the FASTA file for REF_PATH.

`bedtools getfasta [OPTIONS] -fi <input FASTA> -bed <BED/GTF/VCF>`

With this resulting file, I ran `psite train` but it didn't complete. There is no pickle trained models as results, only a log file per sample that looks like this:

```
# TxInfo: txinfo.tsv
# Transcript quant: None
# Alignment file: ../bam/CTR_1.Aligned.toTranscriptome.out.sorted.bam
# nts                     = 3
# train_offset_min        = 10
# train_offset_max        = 14
# train_max_depth         = 3
# train_min_samples_split = 6
# ...load reference fasta
# ...load gene information
# ...get representative transcript per gene
# ...keep items common in ref fasta and txinfo
# ...check metada
# Empty DataFrame
# Columns: [tx_name, tx_id, nexon, tx_len, cds_len, utr5_len, utr3_len, gene_name, gene_biotype, transcript_biotype, protein_id, chrom, strand, cds_start_nf, cds_end_nf, mrna_start_nf, mrna_end_nf, start_codon, stop_codon]
# Index: []
#  []
# ...parse alignments
# ...draw QC plots of read length and offset distribution
```
The error message that I receive has something to do with the limits of a plot's axis:

`IndexError: index 0 is out of bounds for axis 0 with size 0`

Please, let me know if I'm working with the right REF_PATH format file, and if so, let me know how to obtain it.
Thanks in advance!

Matias

**Comment by mt1022** [comment]
If you are working with human data, you can download the sequences of all transcripts from ENSEMBL. If you generate that file manually, the IDs produced by bedtools will not match those in the GTF file.

For example, if STAR mapping index was built with
- https://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
- https://ftp.ensembl.org/pub/current_gtf/homo_sapiens/Homo_sapiens.GRCh38.112.gtf.gz

Then, PATH_REF can be obtained as follows.
```
wget https://ftp.ensembl.org/pub/current_fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
wget https://ftp.ensembl.org/pub/current_fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh38.ncrna.fa.gz

zcat Homo_sapiens.GRCh38.cdna.all.fa.gz Homo_sapiens.GRCh38.ncrna.fa.gz | gzip -c > Homo_sapiens.GRCh38.transcripts.fa.gz
```
