### ISSUE TITLE
Question about using PSite output for downstream analyses

### ISSUE THREAD

**Issue by andresferben** [gxelab/psite#2]
Hi there,

I wanted to ask if you analyzed the feasibility of combining PSite's output with [Ribotricer](https://github.com/smithlabcode/ribotricer) for ORF prediction [as you did with Ribo-TISH and RiboCode](https://github.com/gxelab/psite_analysis/blob/main/04_orf_prediction_psite.md). Do you think this would be possible?

Thanks

**Comment by mt1022** [comment]
Hello,
We have not yet attempted this approach. Nonetheless, it is technically feasible. The ribotricer tool infers the P-site offset for each read length and merges reads based on the estimated offsets within the `detect_orfs.py` script. It is plausible that the P-site offset tags per read, as determined by the PSite algorithm, could be utilized at this stage to supersede the offsets estimated by ribotricer.
For more details, you can refer to the relevant section of the `detect_orfs.py` script in the ribotricer repository: [detect_orfs.py](https://github.com/smithlabcode/ribotricer/blob/7a7d8e2a95a55466f5d2fad3219533583532b804/ribotricer/detect_orfs.py#L47).

**Comment by andresferben** [comment]
Thanks! I'll take a look at it.
